# Generated by Django 5.2.7 on 2025-12-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
