# Generated by Django 6.0 on 2025-12-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_suppliers_alter_order_supplier_alter_rating_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=200),
        ),
    ]
