# Generated by Django 6.0 on 2025-12-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_suppliers_gas_brand_suppliers_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='supplier_images/'),
        ),
    ]
