# Generated by Django 6.0 on 2025-12-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_suppliers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='image',
            field=models.ImageField(upload_to='supplier_images/'),
        ),
    ]
