# Generated by Django 6.0 on 2025-12-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_suppliers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='image',
            field=models.ImageField(default='default.svg', upload_to=''),
        ),
    ]
