# Generated by Django 6.0 on 2025-12-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_suppliers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_images/'),
        ),
    ]
